In [1]:
idx = [0,1,2]

In [2]:
indx

NameError: name 'indx' is not defined

In [3]:
idx


[0, 1, 2]

In [4]:
x = [1,2,3]

In [5]:
x

[1, 2, 3]

In [6]:
x[idx]

TypeError: list indices must be integers or slices, not list

In [1]:
import torch

In [2]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [6]:
x = torch.tensor([0,1,0,0,1,1])

In [7]:
x

tensor([0, 1, 0, 0, 1, 1])

In [8]:
labels = torch.eye(2)[x.long(), :]

In [9]:
labels

tensor([[1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.]])

In [10]:
f = nn.BCEWithLogitsLoss()

NameError: name 'nn' is not defined

In [11]:
import torch.nn as nn 
f = nn.BCEWithLogitsLoss()

In [12]:
f = nn.BCEWithLogitsLoss()

In [13]:
x = torch.tensor([-0.2241,  0.3044])

In [14]:
x


tensor([-0.2241,  0.3044])

In [15]:
y = torch.tensor([0., 1.])

In [16]:
y

tensor([0., 1.])

In [17]:
f(x,y)

tensor(0.5699)