In [1]:
import torch
import torch.nn as nn 


In [2]:
print(torch.__version__)

1.8.1+cu111


In [7]:
x = [1.0,2,3,4]
x

[1.0, 2, 3, 4]

In [8]:
y= torch.Tensor(x)
y

tensor([1., 2., 3., 4.])

In [9]:
z = torch.FloatTensor(y)
z

tensor([1., 2., 3., 4.])

In [12]:
type(z)

torch.Tensor

In [14]:
m = torch.cuda.FloatTensor(x)
m

tensor([1., 2., 3., 4.], device='cuda:0')