In [78]:
import torch
import torch.nn as nn 
criterion = torch.nn.BCEWithLogitsLoss()

In [79]:
out = torch.rand((2,2))
out

tensor([[0.9502, 0.2922],
        [0.7435, 0.0411]])

In [80]:
labels = torch.tensor([0,1])
labels


tensor([0, 1])

In [81]:
labels = torch.eye(2)[labels.long(), :]
labels

tensor([[1., 0.],
        [0., 1.]])

In [82]:
criterion(out,labels)

tensor(0.7455)