In [1]:
import torch
import torch.nn as nn 

In [2]:
x = torch.rand((64,256,4,4))

In [3]:
x

tensor([[[[0.2055, 0.5477, 0.2492, 0.5379],
          [0.7713, 0.4739, 0.8636, 0.4633],
          [0.4549, 0.1481, 0.7247, 0.3495],
          [0.3704, 0.5210, 0.9300, 0.9613]],

         [[0.3749, 0.0532, 0.9565, 0.5108],
          [0.8368, 0.4631, 0.9062, 0.4952],
          [0.3159, 0.1771, 0.6785, 0.8722],
          [0.7236, 0.7169, 0.8834, 0.2396]],

         [[0.6401, 0.6898, 0.7254, 0.6046],
          [0.1296, 0.6675, 0.1917, 0.5752],
          [0.9582, 0.4112, 0.2006, 0.2253],
          [0.6817, 0.7104, 0.1307, 0.2411]],

         ...,

         [[0.1065, 0.8376, 0.2209, 0.4112],
          [0.1823, 0.9886, 0.5668, 0.1630],
          [0.6994, 0.2812, 0.1320, 0.0652],
          [0.3128, 0.2804, 0.3526, 0.1749]],

         [[0.4652, 0.4446, 0.6942, 0.1989],
          [0.5884, 0.4054, 0.9811, 0.2279],
          [0.4648, 0.2260, 0.6921, 0.7696],
          [0.8949, 0.4636, 0.1434, 0.5137]],

         [[0.0870, 0.8079, 0.2505, 0.7881],
          [0.6486, 0.2308, 0.2726, 0.7683],
       

In [4]:
y = torch.flatten(x,1)

In [5]:
y

tensor([[0.2055, 0.5477, 0.2492,  ..., 0.9264, 0.3707, 0.2801],
        [0.8100, 0.9017, 0.5924,  ..., 0.0488, 0.7060, 0.8686],
        [0.0389, 0.5733, 0.9637,  ..., 0.3665, 0.3568, 0.2591],
        ...,
        [0.9463, 0.1638, 0.1122,  ..., 0.2247, 0.4165, 0.4532],
        [0.4046, 0.2880, 0.3514,  ..., 0.2252, 0.3590, 0.9262],
        [0.4987, 0.9325, 0.4089,  ..., 0.2325, 0.1820, 0.7205]])

In [6]:
y.shape

torch.Size([64, 4096])

In [7]:
x1 = torch.rand((64,256,2,2))

In [8]:
x1

tensor([[[[0.6295, 0.0162],
          [0.0688, 0.5633]],

         [[0.2687, 0.4960],
          [0.0253, 0.6889]],

         [[0.1495, 0.2477],
          [0.3080, 0.7365]],

         ...,

         [[0.0300, 0.0663],
          [0.9526, 0.7949]],

         [[0.8613, 0.9506],
          [0.5916, 0.0916]],

         [[0.1112, 0.0066],
          [0.7848, 0.5608]]],


        [[[0.4403, 0.4647],
          [0.0316, 0.5716]],

         [[0.5569, 0.8904],
          [0.4991, 0.9856]],

         [[0.3088, 0.4931],
          [0.8602, 0.4219]],

         ...,

         [[0.5401, 0.5323],
          [0.4564, 0.4529]],

         [[0.1079, 0.0619],
          [0.6023, 0.9794]],

         [[0.8358, 0.4464],
          [0.9510, 0.3227]]],


        [[[0.3166, 0.9451],
          [0.6394, 0.5660]],

         [[0.4290, 0.2466],
          [0.8476, 0.1837]],

         [[0.3387, 0.7353],
          [0.5181, 0.7913]],

         ...,

         [[0.1652, 0.0740],
          [0.2384, 0.9584]],

         [[0.4115, 0.55

In [9]:
z = torch.flatten(x1,1)

In [10]:
z

tensor([[0.6295, 0.0162, 0.0688,  ..., 0.0066, 0.7848, 0.5608],
        [0.4403, 0.4647, 0.0316,  ..., 0.4464, 0.9510, 0.3227],
        [0.3166, 0.9451, 0.6394,  ..., 0.6572, 0.8436, 0.3812],
        ...,
        [0.9618, 0.4686, 0.2030,  ..., 0.4170, 0.0610, 0.8612],
        [0.1550, 0.0708, 0.4732,  ..., 0.2379, 0.8419, 0.6574],
        [0.3674, 0.4164, 0.4963,  ..., 0.2053, 0.9078, 0.3560]])

In [11]:
z.shape

torch.Size([64, 1024])

In [12]:
x2 = torch.rand((64,256,1,1))

In [13]:
x2

tensor([[[[0.3047]],

         [[0.1461]],

         [[0.2044]],

         ...,

         [[0.3134]],

         [[0.1048]],

         [[0.8146]]],


        [[[0.1789]],

         [[0.4740]],

         [[0.6658]],

         ...,

         [[0.6625]],

         [[0.5047]],

         [[0.6425]]],


        [[[0.3950]],

         [[0.6476]],

         [[0.1857]],

         ...,

         [[0.9424]],

         [[0.2213]],

         [[0.3578]]],


        ...,


        [[[0.1032]],

         [[0.4629]],

         [[0.0900]],

         ...,

         [[0.6379]],

         [[0.0305]],

         [[0.7345]]],


        [[[0.4928]],

         [[0.2938]],

         [[0.1110]],

         ...,

         [[0.3278]],

         [[0.1062]],

         [[0.5126]]],


        [[[0.4756]],

         [[0.9495]],

         [[0.4102]],

         ...,

         [[0.5442]],

         [[0.1097]],

         [[0.5452]]]])

In [14]:
t = torch.flatten(x2,1)

In [15]:
t

tensor([[0.3047, 0.1461, 0.2044,  ..., 0.3134, 0.1048, 0.8146],
        [0.1789, 0.4740, 0.6658,  ..., 0.6625, 0.5047, 0.6425],
        [0.3950, 0.6476, 0.1857,  ..., 0.9424, 0.2213, 0.3578],
        ...,
        [0.1032, 0.4629, 0.0900,  ..., 0.6379, 0.0305, 0.7345],
        [0.4928, 0.2938, 0.1110,  ..., 0.3278, 0.1062, 0.5126],
        [0.4756, 0.9495, 0.4102,  ..., 0.5442, 0.1097, 0.5452]])

In [16]:
t.shape

torch.Size([64, 256])

In [17]:
y+z+t

RuntimeError: The size of tensor a (4096) must match the size of tensor b (1024) at non-singleton dimension 1

In [19]:
p = torch.cat((y,z,t),dim=1)

In [20]:
p

tensor([[0.2055, 0.5477, 0.2492,  ..., 0.3134, 0.1048, 0.8146],
        [0.8100, 0.9017, 0.5924,  ..., 0.6625, 0.5047, 0.6425],
        [0.0389, 0.5733, 0.9637,  ..., 0.9424, 0.2213, 0.3578],
        ...,
        [0.9463, 0.1638, 0.1122,  ..., 0.6379, 0.0305, 0.7345],
        [0.4046, 0.2880, 0.3514,  ..., 0.3278, 0.1062, 0.5126],
        [0.4987, 0.9325, 0.4089,  ..., 0.5442, 0.1097, 0.5452]])

In [21]:
p.shape

torch.Size([64, 5376])