In [1]:
import numpy as np 

In [2]:
x = [i+1 for i in range(3*5)]

In [3]:
x

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [4]:
y = np.array(x)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
z = y.reshape(3,5)

In [9]:
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
m = z.transpose()

m

In [11]:
m

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [12]:
m.size

15

In [13]:
m.shape

(5, 3)

In [14]:
col = m.shape[1]

In [15]:
col


3

In [41]:
for i in range(col):
    if i%2 !=0:
        x = np.sort(m[:,i])
        x = np.array(sorted(list(x),reverse=True))
        m[:,i] = x

In [42]:
type(x)

numpy.ndarray

In [43]:
x

array([10,  9,  8,  7,  6])

In [44]:
m

array([[ 1, 10, 11],
       [ 2,  9, 12],
       [ 3,  8, 13],
       [ 4,  7, 14],
       [ 5,  6, 15]])

In [36]:
x = np.array(sorted(list(x),reverse=True))

In [37]:
x

array([10,  9,  8,  7,  6])