In [24]:
import torch

In [25]:
x = torch.tensor([[0.03,-0.03],[-0.02,0.02]])

In [27]:
# 取最大值的索引
x.max(-1)

torch.return_types.max(
values=tensor([0.0300, 0.0200]),
indices=tensor([0, 1]))

In [47]:
y = x.max(-1)[-1]==1

In [48]:
y

tensor([False,  True])

In [49]:
z = y.float()

In [50]:
z

tensor([0., 1.])

In [51]:
z.mean()

tensor(0.5000)

In [52]:
z

tensor([0., 1.])

In [53]:
m = z.mean()

In [54]:
m

tensor(0.5000)