In [21]:
import torch

In [22]:
x = [[-0.01,0.01],[0.02,-0.02],[0.03,-0.03]]

In [23]:
x

[[-0.01, 0.01], [0.02, -0.02], [0.03, -0.03]]

In [24]:
y = [1,0,1]

In [25]:
y

[1, 0, 1]

In [26]:
x,y = torch.tensor(x),torch.tensor(y)

In [27]:
x

tensor([[-0.0100,  0.0100],
        [ 0.0200, -0.0200],
        [ 0.0300, -0.0300]])

In [28]:
y

tensor([1, 0, 1])

In [29]:
x.max(-1)

torch.return_types.max(
values=tensor([0.0100, 0.0200, 0.0300]),
indices=tensor([1, 0, 0]))

In [30]:
x.max(-1)[-1]

tensor([1, 0, 0])

In [31]:
 z = x.max(-1)[-1] == y

In [32]:
z

tensor([ True,  True, False])

In [33]:
t = z.float()

In [34]:
t.mean()

tensor(0.6667)