In [1]:
import torch
import torch.nn as nn 


In [2]:
cerition = nn.BCELoss()

In [5]:
x = [[-0.01,0.01]]

In [6]:
x

[[-0.01, 0.01]]

In [7]:
tar = [1]

In [8]:
tar

[1]

In [9]:
tar = torch.tensor(tar)

In [12]:
# 1 one hot编码 使得input 和 target 的shape一样（若shape一致直接带入计算）
one_hot_tar = torch.eye(2)[tar.long(),:]

In [13]:
one_hot_tar

tensor([[0., 1.]])

In [17]:
x_tensor = torch.tensor(x)

In [18]:
x_tensor.shape

torch.Size([1, 2])

In [19]:
one_hot_tar.shape

torch.Size([1, 2])

In [23]:
x_tensor

tensor([[-0.0100,  0.0100]])

In [24]:
# 2 input要使用Sigmoid()缩放到[0,1]之间
sig = nn.Sigmoid()

In [26]:
sig_x_tensor = sig(x_tensor)

In [27]:
sig_x_tensor

tensor([[0.4975, 0.5025]])

In [29]:
# 3 使用BCELoss进行计算

cerition(sig_x_tensor,one_hot_tar)

tensor(0.6882)